### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [tex2e/rfc-translater#28]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：
https://github.com/tex2e/rfc-translater/blob/51597c534f577166ae0e21397d2a136300387d22/html/rfc8024.html

**Comment by tex2e** [comment]
If you want to delete a sensitive data, please give me a pull request.
